plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.4'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
}


repositories {
    mavenCentral()
}

dependencies {
    // jpa
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // web
    implementation 'org.springframework.boot:spring-boot-starter-web'
    // lombok
    compileOnly 'org.projectlombok:lombok'
    implementation 'jakarta.xml.bind:jakarta.xml.bind-api:4.0.2'

    // DataBase
    runtimeOnly 'org.mariadb.jdbc:mariadb-java-client:3.5.4'

    annotationProcessor 'org.projectlombok:lombok'


    // security
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    // redisson
    implementation 'org.redisson:redisson-spring-boot-starter:3.23.1'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

    // RabbitMQ
    implementation 'org.springframework.boot:spring-boot-starter-amqp'

    // WebSocket + STOMP + SockJS
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    // await
    testImplementation 'org.awaitility:awaitility:4.2.0'

    // Mockito
    testImplementation 'org.mockito:mockito-core:5.17.0'

    //fcm
    implementation 'com.google.firebase:firebase-admin:9.4.1'

    // AWS S3
    implementation 'software.amazon.awssdk:s3:2.21.0'
    implementation 'software.amazon.awssdk:sts:2.21.0'

    //mongodb
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'

    // validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // mail
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    // 테스트
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

    // OPENSEARCH
    implementation 'org.opensearch.client:opensearch-rest-client:2.11.0'
    implementation 'org.opensearch.client:opensearch-java:2.11.0'
    implementation 'jakarta.json:jakarta.json-api:2.1.3'
}

tasks.named('test') {
    useJUnitPlatform()

    systemProperty 'file.encoding', 'UTF-8'


    testLogging {
        events 'passed', 'skipped', 'failed', 'standardOut', 'standardError'
        exceptionFormat 'full'
        showExceptions true
        showCauses true
        showStackTraces true
    }

    afterTest { descriptor, result ->
        def status
        switch (result.resultType) {
            case org.gradle.api.tasks.testing.TestResult.ResultType.SUCCESS:
                status = 'PASS'
                break
            case org.gradle.api.tasks.testing.TestResult.ResultType.FAILURE:
                status = 'FAIL'
                break
            case org.gradle.api.tasks.testing.TestResult.ResultType.SKIPPED:
                status = 'SKIP'
                break
            default:
                status = result.resultType.toString()
        }

        println "[${status}] ${descriptor.className} > ${descriptor.name}"
    }

    afterSuite { descriptor, result ->
        if (descriptor.parent == null) {
            println ''
            println '==================== TEST SUMMARY ===================='
            println "ALL TEST     : ${result.testCount}"
            println "SUCCESS      : ${result.successfulTestCount}"
            println "FAILURE      : ${result.failedTestCount}"
            println "SKIP         : ${result.skippedTestCount}"
            println "RESULT       : ${result.resultType}"
            println '======================================================'
        }
    }
}
