#apiVersion: v1
#kind: Secret
#metadata:
#  name: auction-back-secret
#  namespace: auction
#type: Opaque
#stringData:
#  SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
#  SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
#  SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
#
#  SPRING_DATA_MONGODB_URI: "${SPRING_DATA_MONGODB_URI}"
#
#  SPRING_DATA_REDIS_HOST: "${SPRING_DATA_REDIS_HOST}"
#  SPRING_DATA_REDIS_PASSWORD: "${SPRING_DATA_REDIS_PASSWORD}"
#
#  SPRING_RABBITMQ_HOST: "${SPRING_RABBITMQ_HOST}"
#  SPRING_RABBITMQ_USERNAME: "${SPRING_RABBITMQ_USERNAME}"
#  SPRING_RABBITMQ_PASSWORD: "${SPRING_RABBITMQ_PASSWORD}"
#
#  MAIL_USERNAME: "${MAIL_USERNAME}"
#  MAIL_PASSWORD: "${MAIL_PASSWORD}"
#
#  FIREBASE_SERVICE_ACCOUNT_B64: "${FIREBASE_SERVICE_ACCOUNT_B64}"
#  AES_GCM_KEY_B64: "${AES_GCM_KEY_B64}"
#
#  TOKEN_HASH_KEY_B64: "${TOKEN_HASH_KEY_B64}"
#  TOKEN_HASH_SECRET: "${TOKEN_HASH_SECRET}"
#
#  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
#  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
#
#  JWT_SECRET_KEY_RT: "${JWT_SECRET_KEY_RT}"